[template]
sub_templates = [
  # Entrypoint templates
  "workspace",
  "standalone-contract",
  # Contract templates in workspace
  "contract",
  "atomics-contract",
  "stack-reorder-contract",
  "add-debugger-contract"
  # Dependency crate templates
  "c-wrapper-crate",
  "x64-simulator-crate",
]
